#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

cd ~/app-root/data/perl-new/bin
#Development Server
#nohup ./perl $OPENSHIFT_REPO_DIR/MyApp/script/myapp_server.pl -r -p $OPENSHIFT_DIY_PORT -h $OPENSHIFT_DIY_IP  >> $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &

#FastCGI
#nohup ./perl $OPENSHIFT_REPO_DIR/MyApp/script/myapp_fastcgi.pl --listen $OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT  >> $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &

#Just for testing
#./perl $OPENSHIFT_REPO_DIR/MyApp/script/myapp_fastcgi.pl --listen $OPENSHIFT_DIY_IP:15000  

# $OPENSHIFT_INTERNAL_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_DIY_LOG_DIR/server.log 2>&1 &
# replace the $OPENSHIFT_INTERNAL_IP and $OPENSHIFT_INTERNAL_PORT before starting up the server

#sed -e "s/`echo '$OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT'`/`echo $OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT`/" $OPENSHIFT_DATA_DIR/conf/nginx.conf.template > $OPENSHIFT_DATA_DIR/conf/nginx.conf

#nohup $OPENSHIFT_DATA_DIR/sbin/nginx >> $OPENSHIFT_DIY_LOG_DIR/server.log 2>&1 &
