#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

# The logic to stop your application should be put in this script.

# Regular Catalyst Development server
if [ -z "$(ps -ef | grep myapp_server.pl | grep -v grep)" ]
then
    client_result "Development Application is already stopped"
else
    kill `ps -ef | grep myapp_server.pl | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
    client_result "Killing development server"
fi


#FASTCGI Production
#Not sure if this stops it or not
if [ -z "$(ps -ef | grep myapp_fastcgi.pl | grep -v grep)" ]
then
    client_result "FASTCGI Application is already stopped"
else
    kill `ps -ef | grep myapp_fastcgi.pl | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
    client_result "Killing fastcgi server"
fi


if [ -z "$( lsof -i tcp:8080)" ]
then 
    client_result "Nothing running on port 8080"
else
    kill `lsof -i tcp:8080 | grep -v COMMAND | awk '{ print $2}'` > /dev/null 2>&1
    client_result "Killing all processes on port 8080"
fi
